name: widget_screenshot_plus
description: 'A fork of widget_screenshot plugin. Flutter package for capturing widgets as high-quality images, including scrollable content. Perfect for sharing app content, creating previews, or saving widget states. Supports PNG/JPEG formats, background customization, and handles complex layouts with ease.'
version: 0.0.1
homepage: 'https://github.com/camilo1498/widget_screenshot_plus'

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.widget_screenshot_plus
        pluginClass: WidgetScreenshotPlusPlugin
      ios:
        pluginClass: WidgetScreenshotPlusPlugin