name: widget_screenshot_plus
description: "A fork of widget_screenshot plugin, updated for flutter 3.32.0"
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.widget_screenshot_plus
        pluginClass: WidgetScreenshotPlusPlugin
      ios:
        pluginClass: WidgetScreenshotPlusPlugin