name: widget_screenshot_plus
description: 'Capture Flutter widgets as images with scrollable content support. Export to PNG/JPEG with custom backgrounds. Perfect for sharing UI states or generating previews.'
version: 0.0.5
homepage: 'https://github.com/camilo1498/widget_screenshot_plus'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.widget_screenshot_plus
        pluginClass: WidgetScreenshotPlusPlugin
      ios:
        pluginClass: WidgetScreenshotPlusPlugin